param(
    [Parameter(Mandatory = $true)]
    [string]$Path,

    [switch]$ExcludeGenerated,

    [int]$DuplicateBlockSize = 6
)

$root = Resolve-Path -LiteralPath $Path
$files = Get-ChildItem -LiteralPath $root -Recurse -Filter *.java

if ($ExcludeGenerated) {
    $files = $files | Where-Object {
        $contentHead = (Get-Content -LiteralPath $_.FullName -TotalCount 40) -join "`n"
        $_.Name -notlike "*Example.java" -and
        $contentHead -notmatch "generated by MyBatis Generator"
    }
}

$fileMetrics = @()
$allBlocks = @{}

foreach ($file in $files) {
    $lines = Get-Content -LiteralPath $file.FullName
    $nonBlank = @($lines | Where-Object { $_.Trim().Length -gt 0 }).Count
    $imports = @($lines | Where-Object { $_ -match "^\s*import\s+" }).Count
    $methods = @($lines | Where-Object { $_ -match "^\s*(public|private|protected)\s+[\w\<\>\[\],\s\?]+\s+\w+\s*\(" }).Count
    $autowired = @($lines | Where-Object { $_ -match "@Autowired" }).Count

    $smells = New-Object System.Collections.Generic.List[string]
    if ($nonBlank -ge 300) { $smells.Add("LargeClass") }
    if ($methods -ge 20) { $smells.Add("ManyMethods") }
    if ($imports -ge 25) { $smells.Add("HighCouplingImports") }
    if ($autowired -ge 8) { $smells.Add("ManyInjectedDependencies") }
    if ($file.FullName -match "\\controller\\" -and (($lines -join "`n") -match "(Mapper|Repository|Dao)")) {
        $smells.Add("ControllerTouchesPersistence")
    }

    $relative = Resolve-Path -LiteralPath $file.FullName -Relative
    $fileMetrics += [PSCustomObject]@{
        File = $relative
        LOC = $nonBlank
        Imports = $imports
        Methods = $methods
        Autowired = $autowired
        Smells = ($smells -join ",")
        SmellCount = $smells.Count
        GodModule = ($nonBlank -ge 500 -or $methods -ge 30)
    }

    $normalized = @(
        $lines |
            ForEach-Object { $_.Trim() } |
            Where-Object {
                $_.Length -gt 0 -and
                $_ -notmatch "^//" -and
                $_ -notmatch "^\*" -and
                $_ -notmatch "^/\*" -and
                $_ -notmatch "^package " -and
                $_ -notmatch "^import "
            }
    )

    for ($i = 0; $i -le $normalized.Count - $DuplicateBlockSize; $i++) {
        $block = ($normalized[$i..($i + $DuplicateBlockSize - 1)] -join " ")
        if ($block.Length -lt 80) { continue }
        if (-not $allBlocks.ContainsKey($block)) {
            $allBlocks[$block] = New-Object System.Collections.Generic.HashSet[string]
        }
        [void]$allBlocks[$block].Add($relative)
    }
}

$duplicateInstances = 0
foreach ($entry in $allBlocks.GetEnumerator()) {
    if ($entry.Value.Count -gt 1) {
        $duplicateInstances += $entry.Value.Count
    }
}

$moduleCount = @($fileMetrics).Count
$smellCount = @($fileMetrics | Measure-Object -Property SmellCount -Sum).Sum
if ($null -eq $smellCount) { $smellCount = 0 }
$godCount = @($fileMetrics | Where-Object { $_.GodModule }).Count

[PSCustomObject]@{
    Path = $root.Path
    ExcludeGenerated = [bool]$ExcludeGenerated
    Modules = $moduleCount
    Smells = [int]$smellCount
    GodModules = $godCount
    DuplicateInstances = $duplicateInstances
    CSD = if ($moduleCount -gt 0) { [math]::Round($smellCount / $moduleCount, 3) } else { 0 }
    GMR = if ($moduleCount -gt 0) { [math]::Round($godCount / $moduleCount, 3) } else { 0 }
    DSI = if ($moduleCount -gt 0) { [math]::Round($duplicateInstances / $moduleCount, 3) } else { 0 }
}

"`nTop smell candidates:"
$fileMetrics |
    Sort-Object SmellCount, LOC -Descending |
    Select-Object -First 15 File, LOC, Imports, Methods, Autowired, Smells, GodModule |
    Format-Table -AutoSize

